#!/bin/bash

# Ngrok setup script for consistent tunnel URLs
# Ngrok provides more predictable URLs than Cloudflare's random ones

echo "======================================"
echo "NGROK SETUP FOR MOBILE TESTING"
echo "======================================"
echo ""
echo "Ngrok provides more stable URLs than Cloudflare tunnel:"
echo "- Free tier: URLs like https://abc123.ngrok.io (semi-random but consistent for 8 hours)"
echo "- Paid tier: Custom subdomains like https://my-app.ngrok.io"
echo ""
echo "SETUP STEPS:"
echo "1. Install ngrok:"
echo "   brew install ngrok  (Mac)"
echo "   Or download from https://ngrok.com/download"
echo ""
echo "2. Create free account at https://ngrok.com"
echo ""
echo "3. Add your authtoken:"
echo "   ngrok authtoken YOUR_TOKEN_HERE"
echo ""
echo "4. Start tunnel for frontend:"
echo "   ngrok http 5173"
echo ""
echo "5. In another terminal, tunnel backend:"
echo "   ngrok http 3001"
echo ""
echo "The URLs will be shown and remain stable for your session."
echo ""
echo "======================================"
echo "PRO TIP: Save URLs in .env.local"
echo "======================================"
echo "VITE_NGROK_URL=https://your-id.ngrok.io"
echo "VITE_API_BASE_URL=https://your-backend-id.ngrok.io/api"